### ISSUE TITLE
Specify directory where workflows are located

### ISSUE THREAD

**Issue by FalconerTC** [rhysd/actionlint#108]
Actionlint does auto-discover of workflows but that means it can't be guided when in a repo with multiple directories of workflows. I'd like to use it in a repo that we use to template and deploy Github Actions but it defaults always to the root `.github/workflows` instead. A flag to configure this would be handy

**Comment by tateexon** [comment]
I am in a similar situation and thus would very much like this as well!

**Comment by rhysd** [comment]
How about the following?

```sh
actionlint ./your/workflows/dir/**/*.yml
```

**Comment by tateexon** [comment]
Yes that would work!

**Comment by rhysd** [comment]
Let me close this for now. If someone finds some case where [the usage](https://github.com/rhysd/actionlint/issues/108#issuecomment-1166168040) does not work, please let me know by leaving a comment in this issue.
