### ISSUE TITLE
Issue with actionlint 1.6.8 when using Azure OpenID Connect 

### ISSUE THREAD

**Issue by sodds-eq** [rhysd/actionlint#112]
From README.md in azure/login@v1:

    # File: .github/workflows/OIDC_workflow.yml
    name: Run Azure Login with OIDC
    on: [push]

      permissions:
      id-token: write
      contents: read
    jobs:
      build-and-deploy:
        runs-on: ubuntu-latest
         steps:
          - name: 'Az CLI login'
            uses: azure/login@v1
            with:
              client-id: ${{ secrets.AZURE_CLIENT_ID }}
              tenant-id: ${{ secrets.AZURE_TENANT_ID }}
              subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

This causes actionlint to report errors related to the client-id, tenant-id and subscription-id references(which in the latest v1 are listed as required input if using OIDC)

    sp.yml:34:15: missing input "creds" which is required by action "azure/login@v1". all required inputs are "creds" [action]
       |
    34 |         uses: azure/login@v1
       |               ^~~~~~~~~~~~~~
    sp.yml:36:11: input "client-id" is not defined in action "azure/login@v1". available inputs are "allow-no-subscriptions", "creds",     "enable-AzPSSession", "environment" [action]
    |
    36 |           client-id: ${{ secrets.AZURE_CLIENT_ID }}
    |           ^~~~~~~~~~
    sp.yml:37:11: input "tenant-id" is not defined in action "azure/login@v1". available inputs are "allow-no-subscriptions", "creds", "enable-AzPSSession", "environment" [action]
    |
    37 |           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
    |           ^~~~~~~~~~
    sp.yml:38:11: input "subscription-id" is not defined in action "azure/login@v1". available inputs are "allow-no-subscriptions", "creds", "enable-AzPSSession", "environment" [action]
    |
    38 |           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

**Comment by shogo82148** [comment]
It looks to be fixed by https://github.com/rhysd/actionlint/commit/f21cdb8c37e4b2fda20648faba85c0537de1fa07, but it is not released.
@rhysd Can you create a new release, or may I help you?

**Comment by rhysd** [comment]
I confirmed this no longer happens with the reporter's repro with v1.6.11. Closing.
