### ISSUE TITLE
Docs: Shellcheck suppressions via actionlint.yaml config file

### ISSUE THREAD

**Issue by ViacheslavKudinov** [rhysd/actionlint#156]
Hello,
there is no documentation how to set **suppression** for built-in `shellcheck` functionality.
I can use env variables, but then it will change usual `shellcheck` tests as well, and that is not what i need.

It will be great to get examples how to configure it in `actionlint.yaml` or, maybe, disable `shellcheck` as a workaround.

**Comment by mohamed-haidara-cko** [comment]
Ah ok, got it :-)

**Comment by seemethere** [comment]
Also interested in this as well, it's annoying to have to pass these on the command line directly

**Comment by rhysd** [comment]
To disable shellcheck integration, please pass empty string to `-shellcheck` option.

```sh
actionlint -shellcheck=
```

Adding some config would be useful for some situation, but I'm trying to keep configuration file as minimal as possible.

**Comment by maxisam** [comment]
you can use ACTION_ACTIONLINT_ARGUMENTS to add -ignore in `.mega-linter.yml`
