### ISSUE TITLE
false positive about the input of octokit/request-action@v2.x

### ISSUE THREAD

**Issue by iwata** [rhysd/actionlint#16]
`actionlint` allows only `mediaType` and `route` as input for `octokit/request-action@v2.x`.
https://github.com/rhysd/actionlint/blob/main/popular_actions.go#L2415-L2430

But it's false positive, because `request-action` v2 allows other inputs.
ref. https://github.com/octokit/request-action#inputs
They are simply treated as request parameters to the API.

**Comment by rhysd** [comment]
Oh, OK, so request-action allows any request parameters as inputs though they are not defined in `action.yml`. I'll fix this.
