### ISSUE TITLE
Warn about input block of workflow_dispatch event being too long

### ISSUE THREAD

**Issue by witekio-kwe** [rhysd/actionlint#160]
Currently there is a 10 inputs for workflow_dispatch event limit in place.
Every additional input variable makes the whole workflow fail with
`you may only define up to 10 inputs for a workflow_dispatch event`

It would be awesome to avoid it when actionlist warns about this as part of the pre-merge checks

**Comment by rhysd** [comment]
actionlint focuses on finding mistakes so it is not opinionated. And the threshold would not be able to be determined.
