### ISSUE TITLE
idea: vscode extension

### ISSUE THREAD

**Issue by VividLemon** [rhysd/actionlint#185]
It would be cool if this was converted to a vscode extension that created intellisense instead. It would simply check if the file directory is .github/workflows and is .yml/yaml. Then perform the same linting rules. That way I wouldn't need to run cli commands to know if workflows are working, I'd know as I'm doing it.

**Comment by rhysd** [comment]
https://github.com/rhysd/actionlint/blob/main/docs/usage.md#vs-code

**Comment by VividLemon** [comment]
tyvm
