### ISSUE TITLE
Add a warning if you forget`actions/checkout` before running a local action

### ISSUE THREAD

**Issue by stefreak** [rhysd/actionlint#192]
GitHub requires to run `actions/checkout` before running a local action.

It would be nice if the linter could help you notice this early.

**Comment by rhysd** [comment]
How do you detect that not using `actions/checkout` is unintended? Some users may use their own script to checkout sources without `actions/checkout`. In the case, such warning is false positive.

I agree 99% of use cases is using `actions/checkout` to checkout sources, but I'm trying to avoid false positive as much as possible. So this feature basically cannot be implemented.

**Comment by stefreak** [comment]
That's a really good point. Closing this one then. 👍
