### ISSUE TITLE
When a reusable workflow is called with "uses", "strategy" is not available.

### ISSUE THREAD

**Issue by TessaPhillips** [rhysd/actionlint#197]
I'm getting the following action lint error when I am using a reusable workflow with a matrix strategy.

`.github/workflows/lint-and-format.yaml:12:5: when a reusable workflow is called with "uses", "strategy" is not available. only following keys are allowed: "name", "uses", "with", "secrets", "needs", "if", and "permissions" in job "python-pr-lint" [syntax-check]`

As per the documentation, this is valid, and the workflow actually runs fine. Can action lint please be updated to match the documentation? - https://docs.github.com/en/actions/using-workflows/reusing-workflows#example-matrix-strategy-with-a-reusable-workflow

**Comment by seemethere** [comment]
Submitted https://github.com/rhysd/actionlint/pull/199 to resolve

**Comment by rhysd** [comment]
This was made valid very recently (just 2 days ago). So actionlint is not following the update yet.

https://github.blog/changelog/2022-08-22-github-actions-improvements-to-reusable-workflows-2/

> Reusable workflows can now be called from a matrix and other reusable workflows.

**Comment by rhysd** [comment]
This was fixed in [v1.6.17](https://github.com/rhysd/actionlint/releases/tag/v1.6.17).
