### ISSUE TITLE
Reduced size for actionlint in CI

### ISSUE THREAD

**Issue by nvuillam** [rhysd/actionlint#212]
Hi, first thanks for your great tool :)

It is embedded within [Megalinter](https://oxsecurity.github.io/megalinter/latest/descriptors/action_actionlint/) and i'm currently on a hunt for space in docker images

Actionlint install creates & 360mb layer the image, and when I inspect the content I see that there are already lots of apps that are already embedded within MegaLinter (python 3.10, checkov, ktlint, kubeconform, kubeval,cshellcheck, trivy ...), each of them at their latest version (except Python for some incompatibility issues)

Would there be a way to detect such apps if there are already installed , so not install them again ?

Many thanks :)

**Comment by rhysd** [comment]
Hi @nvuillam, thank you for maintaining the project integrating actionlint.

I'm not getting your point. Size of [Docker image of actionlint](https://hub.docker.com/r/rhysd/actionlint/tags) is just 22.17MB. I don't know why your image's layer is so big. [Dockerfile of the image](https://github.com/rhysd/actionlint/blob/main/Dockerfile) may be helpful.

**Comment by nvuillam** [comment]
This is a total mistake, I recently refactored the building of dockerfile to join all the RUN in a single RUN command, and of course actionlint is not installing 360mb of files :)

I apologize, sorry ^^
