### ISSUE TITLE
Download script downloads previous version

### ISSUE THREAD

**Issue by SnowCait** [rhysd/actionlint#218]
I try to download v1.6.17 because actionlint was broken by #216 but v1.6.17 download script downloads v1.6.16.
(Go is not installed in my self-hosted runner, therefore I use download script.)
```bash
bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/v1.6.17/scripts/download-actionlint.bash)
```

v1.6.17 is c9980ce829707101766e3681ace6d67fa7fe5edc.

https://github.com/rhysd/actionlint/blob/c9980ce829707101766e3681ace6d67fa7fe5edc/scripts/download-actionlint.bash#L46

This is caused by release workflow that rewrites download script version **after** tagged.
Download script version should be rewrited **before** tagged.
https://github.com/rhysd/actionlint/blob/0ea32b74cff0913eb53927bd293ef1585a5e14f1/.github/workflows/release.yaml#L1-L5
https://github.com/rhysd/actionlint/blob/0ea32b74cff0913eb53927bd293ef1585a5e14f1/.github/workflows/release.yaml#L34-L44

**Comment by SnowCait** [comment]
It seems to be specifiable with arg but it's not documented and hard to understand because it shows both `main` and `v1.6.17` versions.
https://github.com/rhysd/actionlint/blob/0ea32b74cff0913eb53927bd293ef1585a5e14f1/scripts/download-actionlint.bash#L47-L58

**Comment by rhysd** [comment]
Thanks for the details. I'll fix this at next release.

**Comment by rhysd** [comment]
You're misundesrstanding usage of the script. Give the version as command line option.

https://github.com/rhysd/actionlint/blob/main/scripts/download-actionlint.bash#L33

**Comment by rhysd** [comment]
```bash
bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/v1.6.17/scripts/download-actionlint.bash)
```

is correct.

**Comment by SnowCait** [comment]
@rhysd
>hard to understand because it shows both main and v1.6.17 versions.

My argument is this.
The current usage that fixes script version to `main` is not so good for me.

If you don't want to change usage, would you please document that in [install.md](https://github.com/rhysd/actionlint/blob/main/docs/install.md#download-script)?
That is difficult to find usage that is written in script.

**Comment by rhysd** [comment]
OK, I got your point. I can't change the script interface because it means a breaking change. I'll check document and update it as needed.
