### ISSUE TITLE
The advice about Actions if conditional operators is removed.

### ISSUE THREAD

**Issue by shogo82148** [rhysd/actionlint#22]
actionlint warns if conditions without `${{ ... }}`.

> this expression must be contained within ${{ }} like `if: ${{ ... }}` since it contains operator ".". see https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idif for more details [expression]

but, I can't find its source in https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idif
It looks that it is removed recently: https://github.com/github/docs/pull/8786

**Comment by rhysd** [comment]
Thank you letting me know. The change was *really* recently, just one hour ago: https://github.com/github/docs/pull/8786

We should remove the check.

**Comment by rhysd** [comment]
Since omitting `${{ }}` on `if:` is very common and the advice is raised frequently, I think we need to remove the check and release patch version quickly.

**Comment by rhysd** [comment]
The fix was shipped with v1.5.3 release.

**Comment by shogo82148** [comment]
Thank you for your quickly fix!
