### ISSUE TITLE
Add pre-commit hooks support

### ISSUE THREAD

**Issue by xsc27** [rhysd/actionlint#23]
Making this available as a [pre-commit](https://pre-commit.com/) hook, i.e. add `.pre-commit-hooks.yaml` would be awesome. 😄

**Comment by rhysd** [comment]
I'm not familiar with the tool. Do you mean you'd like to see an example configuration of the tool for actionlint?

**Comment by rally-carlos** [comment]
I would like a `.pre-commit-hook.yaml` to be added to the repo, so `pre-commit` users can point to this repo to use `actionlint` in git hooks. For example, `hadolint` - the Dockfile linting tool, has included one in their repo, https://github.com/hadolint/hadolint/blob/master/.pre-commit-hooks.yaml

It works similarly to how GitHub Actions can point to a repo w/ an `action.yaml` file.

**Comment by xsc27** [comment]
I would like a `.pre-commit-hook.yaml` to be added to the repo, so `pre-commit` users can point to this repo to use `actionlint` in git hooks. For example, `hadolint` - the Dockfile linting tool, has included one in their repo, https://github.com/hadolint/hadolint/blob/master/.pre-commit-hooks.yaml

It works similarly to how GitHub Actions can point to a repo w/ an `action.yaml` file.

**Comment by rhysd** [comment]
Thanks for the explanation. It makes sense. Could you make a PR for this?

**Comment by xsc27** [comment]
Will do 😄

**Comment by rhysd** [comment]
Thank you. It's helpful because you're much more familiar with the tool than me. Please ensure to update [docs/usage.md](https://github.com/rhysd/actionlint/blob/main/docs/usage.md#tools-integration) with its usage.
