### ISSUE TITLE
syntax-check incorrectly rejects run-name key

### ISSUE THREAD

**Issue by norwd** [rhysd/actionlint#230]
I am using action lint as part of [MegaLinter](https://github.com/oxsecurity/megalinter), using version v1.6.16. It is incorrectly flagging `run-name` as an invalid key.

![image](https://user-images.githubusercontent.com/106889957/194456000-9645e74a-8cba-4d21-a862-9969966eacaa.png)

The workflow that it being flagged:

https://github.com/norwd/pword/blob/2c50cabb8c0ca46104c73aa966e057ade1dcf22a/.github/workflows/lint.yml#L2-L6

According to the [documentation](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#run-name) for GitHub workflow syntax, `run-name` is a valid key.

**Comment by rhysd** [comment]
v1.6.16 is old. The latest version supported `run-name`. See changelog for more details.
