### ISSUE TITLE
Alert when `on:` field is missing

### ISSUE THREAD

**Issue by andreasabel** [rhysd/actionlint#232]
`actionlint` accepts a workflow file that has no `on:`, put it is rejected by GitHub: https://github.com/andreasabel/gha-test/actions/runs/3202159936
```
Error: .github#L1
No event triggers defined in `on`
```

**Comment by rhysd** [comment]
Thanks for reporting this. This was a bug of actionlint.

**Comment by rhysd** [comment]
Fix for this issue was shipped at [v1.6.21](https://github.com/rhysd/actionlint/releases/tag/v1.6.21).
