### ISSUE TITLE
set-output is deprecated

### ISSUE THREAD

**Issue by larrys** [rhysd/actionlint#234]
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

I am getting the following warning when running actionlint

The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by Gudahtt** [comment]
actionlint itself is using the deprecated command. e.g. https://github.com/rhysd/actionlint/blob/main/scripts/download-actionlint.bash#L135

Catching usage of this deprecated command would be useful, but I don't think that's what this issue was requesting.

**Comment by rhysd** [comment]
> you mean statically check if a command is deprecated?

No. I meant statically detecting the command is used.

> actionlint itself is using the deprecated command.

Yes. I said this idea would be great if it can be realized without false positive in https://github.com/rhysd/actionlint/issues/234#issuecomment-1277549903.

**Comment by rhysd** [comment]
Today I have some time to implement this with simple pattern matching. I will try it and look if it causes some false positives or not.

**Comment by rhysd** [comment]
[v1.6.22](https://github.com/rhysd/actionlint/releases/tag/v1.6.22) included this feature.
