### ISSUE TITLE
Feature request: lint actions too, not only workflows

### ISSUE THREAD

**Issue by AndreyNautilus** [rhysd/actionlint#243]
`actionlint` does a great job in linting workflows, but repositories may contain individual actions too. It would be nice if `actionlint` can also lint action yaml files (I'm taking mostly about [composite actions](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action) - they may include quite complicated syntax).

**Comment by rhysd** [comment]
This looks duplicate of #46

**Comment by AndreyNautilus** [comment]
Indeed. Please this issue as duplicate in favour of #46 .
