### ISSUE TITLE
Feature request: Basic linting for composite actions

### ISSUE THREAD

**Issue by JavaScriptBach** [rhysd/actionlint#245]
What do you think about adding some basic support for linting composite `action.yml` files? For example:

- Missing `shell:` attribute for steps
- Attempts to access `${{ secrets.* }}`

These are common mistakes that I make when writing actions. In general this project has helped me a lot when writing workflows, and I'd love to get its benefits extended to writing actions!

**Comment by andreypotapov-tomtom** [comment]
Seems like a duplicate of https://github.com/rhysd/actionlint/issues/46

**Comment by AndreyNautilus** [comment]
Seems like a duplicate of https://github.com/rhysd/actionlint/issues/46

**Comment by rhysd** [comment]
Yes, this is duplicate of #46.
