### ISSUE TITLE
Syntax checker update needed

### ISSUE THREAD

**Issue by chester-leung** [rhysd/actionlint#280]
Hi, first, thanks so much for building this!

GitHub recently [released a new change](https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners#running-jobs-on-your-runner) that enables the `runs-on` section of an Actions workflow to have a `labels` and `groups` key under it. However, actionlint will throw an error if we do this:

```bash
.github/workflows/test.yaml:26:7: "runs-on" section must be sequence node but got mapping node with "!!map" tag [syntax-check]
   |
26 |       labels: custom-label
   |       ^~~~~~~
```

Can we please update the linter to reflect these new changes from GitHub? Thank you!

**Comment by mdfaizsiddiqui** [comment]
I am also facing the same problem!
