### ISSUE TITLE
Feature Request `${{ ... }}` cannot be used in Workflow `Name`

### ISSUE THREAD

**Issue by s0undt3ch** [rhysd/actionlint#281]
I tried to use `${{ github.<etc> }}` on the `Name:` of a workflow.

Actionlint did not complain but the job failed to start on GitHub.

**Comment by rhysd** [comment]
`${{ }}` is unavailable in `name`. You need to use `run-name` instead. https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#run-name

**Comment by s0undt3ch** [comment]
Thanks for the info, but should actionlint still thrown an error?

**Comment by s0undt3ch** [comment]
Or even better, suggest the right key to use?

Why did you close the issue?
Error out, or provide the right thing to do is still a valid feature request....
