### ISSUE TITLE
`Action format in uses: ` should error on common branch names

### ISSUE THREAD

**Issue by Bertg** [rhysd/actionlint#284]
Using actions coming from an external source is great. However, we should prefer to specify an exact version when using one.

Quite often I see references to actions like this: `organisation/action@main` or `organisation/action@develop`. This works for a while until the action gets a major new version. 

I would suggest that the library either implements a deny-list of common branch names, (ex: `main, develop,master`) or possibly an allow-list of common release versions (ex `v\d.*`). Obviously the user should be able to add exceptions in their config.

**Comment by rhysd** [comment]
It should not be error because some famous action actually uses `main` ref as normal usage.
