### ISSUE TITLE
Linting action.yaml

### ISSUE THREAD

**Issue by tykeal** [rhysd/actionlint#298]
I really like using actionlint to lint my workflows, but I would love to also be able to lint action.yaml files at the root of a repository themselves for composite actions that I've built. Currently when I specifically point actionlint at an action.yaml it throws a lot of missing section or unexpected keywords.

**Comment by Bertg** [comment]
Yeah, I think many medium to bigger repositories start using these actions to remove duplication from their workflows.
I have already been annoyed a few times assuming it was also validating these files, while it hasn't.

I would try to give it a shot myself, but as I haven't done any `go` so far, I think my efforts would not yield a results any time soon.

**Comment by ianlewis** [comment]
I think this is a duplicate of https://github.com/rhysd/actionlint/issues/46

**Comment by tykeal** [comment]
@ianlewis yes, I thought I had searched for older open issues when I raised this, but I apparently didn't do a good enough job of it!
