### ISSUE TITLE
Support for sparse checkout in actions/checkout

### ISSUE THREAD

**Issue by austinpray-mixpanel** [rhysd/actionlint#305]
![image](https://github.com/rhysd/actionlint/assets/71290498/013298ef-95e1-4a86-bcf7-8ee60f4be71f)

https://github.com/actions/checkout/releases/tag/v3.5.3

https://github.com/actions/checkout/pull/1369

**Comment by austinpray-mixpanel** [comment]
I'm realizing that this might belong on https://github.com/reviewdog/action-actionlint instead

**Comment by dfdez** [comment]
Hey @austinpray-mixpanel as menthioned in the issue this doesn't seem an error of `actions/checkout` more likely to be of [actiolint](https://github.com/reviewdog/action-actionlint)

**Comment by rhysd** [comment]
This will be supported at next release.
