### ISSUE TITLE
Committing/pushing changes made to a different workflow.yml yields remote rejected error

### ISSUE THREAD

**Issue by sla-te** [rhysd/actionlint#313]
```
refusing to allow a GitHub App to create or update workflow `.github/workflows/test.yml` without `workflows` permission
```
stefanzweifel/git-auto-commit-action@v4 is being called from within `.github/workflows/test.yml`. Pushing commited changes made to any other files works just fine.

**Comment by rhysd** [comment]
It doen't look related to actionlint. Please ask it at GitHub's forum.
