### ISSUE TITLE
Add support inputs type: number

### ISSUE THREAD

**Issue by nowsprinting** [rhysd/actionlint#316]
Not supported inputs type `number`.

See: https://docs.github.com/en/actions/learn-github-actions/contexts#inputs-context

e.g.,
```
.github/workflows/example.yml:17:15: input type of workflow_dispatch event must be one of "string", "boolean", "choice", "environment" but got "number" [syntax-check]
```

**Comment by rhysd** [comment]
Thanks for reporting this. I didn't notice `number` type was newly added.

**Comment by nowsprinting** [comment]
Thanks!

> I didn't notice number type was newly added.

Me too. I learned about it yesterday.
