### ISSUE TITLE
Location for actionlint.yaml may be wrong

### ISSUE THREAD

**Issue by jamiet-msm** [rhysd/actionlint#32]
Your documentation (https://github.com/rhysd/actionlint/blob/main/docs/config.md#configuration-file) states:

> Configuration file actionlint.yaml or actionlint.yml can be put in .github directory.

however in order for it to be recognised by SuperLinter I had to put it in .github/linters

**Comment by rhysd** [comment]
The document is correct.

super-linter specifies their own configuration directory by `-config-file` option. So it is different from the place described in the document.

https://github.com/github/super-linter/blob/79dee46012b89640260c6ac33c410809202a8702/lib/linter.sh#L831

**Comment by jamiet-msm** [comment]
> The document is correct.
> 
> super-linter specifies their own configuration directory by `-config-file` option. So it is different from the place described in the document.
> 
> https://github.com/github/super-linter/blob/79dee46012b89640260c6ac33c410809202a8702/lib/linter.sh#L831

Fair enough, thx for the response and correction.
