### ISSUE TITLE
Docs could use info on what kind of regex is used on -ignore

### ISSUE THREAD

**Issue by leemeador** [rhysd/actionlint#320]
There are several formats for regexes out and about in our industry. 

I would like something in the docs that indicate the syntax of the regex used for matching the ignored messages. It could be as simple as some links to official regex docs for whatever type actionlint uses to match the ignored messages.

It might also be good to show one example with single quotes and one with double quotes if both types of quotes are allowed (or indicate its up the the OS parser how that works)

**Comment by rhysd** [comment]
It is the syntax accepted by RE2. I'll update the document.

https://github.com/google/re2/wiki/Syntax

**Comment by leemeador** [comment]
thank you, sir
