### ISSUE TITLE
Bug: actionlint doesn't see property on standard actions/labeler action

### ISSUE THREAD

**Issue by mtirionMSFT** [rhysd/actionlint#328]
**Describe the bug**
I'm using the GitHub standard actions/labeler@v4 in my workflow. The definition can be found here: https://github.com/actions/labeler. The https://github.com/actions/labeler/blob/main/action.yml has the 'dot' variable. 

The linter however says: 
input "dot" is not defined in action "actions/labeler@v4". available inputs are "configuration-path", "repo-token", "sync-labels" [action]
     |
     |           dot: true
     |           ^~~~

**To Reproduce**
Workflow:

name: "Pull Request Labeler"
on: pull_request_target

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - id: label-the-pr
        uses: actions/labeler@v4
        with:
          dot: true
          sync-labels: true

Run the linter. See the error.

**Expected behavior**
No error.

**Comment by rhysd** [comment]
Can you fix your code example in the PR description using ` ``` ` code blocks ? It is hard to understand problem you want to discuss.

**Comment by mtirionMSFT** [comment]
Turned out to be a problem of using the wrong Megalinter version, which was using the older version. Updated that and it all works now. Thanks :)
