### ISSUE TITLE
Support file-level ignore

### ISSUE THREAD

**Issue by azrsh** [rhysd/actionlint#342]
I would like an option to exclude certain workflows from actionlint.
If possible, it would be better to put the option in `actionlint.yml` or a file like  `.actionlintignore` instead of command line options so that the settings can be managed by Git.

Currently, I avoid this problem by specifying files other than "workflows I want to exclude from lint" on the command line.
If there is already a better way, please let me know.

**Comment by HidemaruOwO** [comment]
I'd like that feature too
