### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by suzuki-shunsuke** [rhysd/actionlint#351]
Hi, thank you for your great project!

Do you have any plan to release a new version?

The latest version was released on Jun 16.

https://github.com/rhysd/actionlint/releases/tag/v1.6.25

This isn't so old, but there are many changes between v1.6.25 and `main` branch.

https://github.com/rhysd/actionlint/compare/v1.6.25...main

Especially, I'd like the bug fix #334 .
I really appreciate it if a new version will be out in near future.

Thank you.

**Comment by mathroule** [comment]
I'm waiting for a new release too.

**Comment by shogo82148** [comment]
I asked @rhysd on 𝕏 and he said he'll do it.
Please wait a moment.

**Comment by rhysd** [comment]
Sorry for the delay. I could not take enough time to release due to my personal reason. I'll take time by this weekend.

**Comment by rhysd** [comment]
[v1.6.26](https://github.com/rhysd/actionlint/releases/tag/v1.6.26) has been released.

I'm sorry that the release took so long time. I'd like to make releases more regularly.
