### ISSUE TITLE
No labels for Larger Hosted Runners

### ISSUE THREAD

**Issue by therealdwright** [rhysd/actionlint#371]
In the below announcement, GitHub actions announced some larger runners that are not currently supported in the action lint scanner. For example, when using `labels: ubuntu-latest-16-cores` users will receive the error:

```
label "ubuntu-latest-16-cores" is unknown. available labels are "windows-latest", "windows-2022", "windows-2019", "windows-2016", "ubuntu-latest", "ubuntu-22.04", "ubuntu-20.04", "ubuntu-18.04", "macos-latest", "macos-latest-xl", "macos-13-xl", "macos-13", "macos-13.0", "macos-12-xl", "macos-12", "macos-12.0", "macos-11", "macos-11.0", "macos-10.15", "self-hosted", "x64", "arm", "arm64", "linux", "macos", "windows". if it is a custom label for self-hosted runner, set list of labels in actionlint.yaml config file [runner-label]
```

https://github.blog/changelog/2022-10-20-github-actions-larger-hosted-runners-are-now-automatically-created-for-customers/

**Comment by ericcrosson-bitgo** [comment]
This has been released in https://github.com/rhysd/actionlint/releases/tag/v1.6.27
