### ISSUE TITLE
Lack of `include-hidden-files` for `actions/upload-artifact` 

### ISSUE THREAD

**Issue by Czaki** [rhysd/actionlint#447]
3 days ago the action team decided to add `include-hidden-files` for `actions/upload-artifact@v4` and `actions/upload-artifact@v3`: https://github.com/actions/upload-artifact/issues/602

This is a breaking change performed without bumping the major version. To fix our workflows, we need to use it, but actionlint steep fail https://github.com/napari/napari/pull/7241 

Based on the documentation https://github.com/rhysd/actionlint/blob/main/docs/checks.md#popular-action-inputs-validation-at-with it should be possible to easy regenerate the schema and release a new actionlint version.

**Comment by maikelvdh** [comment]
This should be addressed by https://github.com/rhysd/actionlint/pull/446

**Comment by Czaki** [comment]
For anyone who is stucked with this action failing, you may change `uses: actions/upload-artifact@v4` to `uses: actions/upload-artifact@v4.4.0` and this will disable actionlint validation of input parameters.

**Comment by rhysd** [comment]
This issue should be fixed by [v1.7.2](https://github.com/rhysd/actionlint/releases/tag/v1.7.2).
