### ISSUE TITLE
Do runner labels `macos-12.0`, `macos-13.0`, and `macos-14.0` exist?

### ISSUE THREAD

**Issue by muzimuzhi** [rhysd/actionlint#452]
`actionlint` accepts four `macos-X.0` (`X` is one of 11, 12, 13, 14) runner labels, but none of them are found in the [list of labels](https://github.com/actions/runner-images?tab=readme-ov-file#available-images) for GitHub-hosted runner images.

Among them `macos-11.0` once existed (see https://github.com/actions/runner-images/issues/1814), is deprecated now and PR #451 proposed its removal. But I doubt whether other `maxos-X.0` labels ever existed.

I tested using `runs-on: macos-14.0` in https://github.com/muzimuzhi/hello-github-actions/pull/39/commits/c5f0e6ab8d7c483540c16293ef3a11dc296aa9c6, and the job hanged at "Waiting for a runner to pick up this job...", quite the case when an invalid runner label was used.

**Comment by muzimuzhi** [comment]
It seems currently any invalid runner label just makes the job hung, see more experiments in https://github.com/muzimuzhi/hello-github-actions/pull/39 and a similar discussion in https://github.com/orgs/community/discussions/31587.

**Comment by rhysd** [comment]
Okay, so we can think that `macos-12.0`, `macos-13.0`, ... are not existing.
