### ISSUE TITLE
New context variable `github.run_attempt` fails validation

### ISSUE THREAD

**Issue by rbayliss** [rhysd/actionlint#57]
The GHA runner recently added a new context property added to the `github` object: `run_attempt`. This property was added in [v2.283.0](https://github.com/actions/runner/releases/tag/v2.283.0).

Using this property currently fails actionlint validation with `property "run_attempt" is not defined in object type...`.

**Comment by rhysd** [comment]
Thanks for reporting it. I'll work on approximately tomorrow.

**Comment by rhysd** [comment]
This fix was released at v1.6.5.
