### ISSUE TITLE
actionlint rejects the valid needs.<id>.result property

### ISSUE THREAD

**Issue by sjagoe** [rhysd/actionlint#60]
I'm looking at using `actionlint`, and busy testing it on a few workflows. It's working really well and the integration with shellcheck is a huge saver.

The one problem I have encountered is this:
```
.github/workflows/master_push.yml:165:213: property "result" is not defined in object type {} [expression]
```

The step in question uses the `${{ needs.build.result }}` context expression, where `build` is a previous job in the workflow, in the `needs` list for this job. `result` is a valid property of the needs context, documented here: https://docs.github.com/en/actions/learn-github-actions/contexts#needs-context

**Comment by rhysd** [comment]
No problem. I'm glad to hear that actionlint could catch the mistake :+1:
