### ISSUE TITLE
Provide ExecKindInvalid / ExecInvalid for invalid step declaration

### ISSUE THREAD

**Issue by catthehacker** [rhysd/actionlint#81]
Example: https://github.com/catthehacker/actlint/commit/0ff2df586f1eee57e71556f15bc136eaf7a5e1b1

In https://github.com/nektos/act we have more than just `action`/`run` types but it would help us (and not only us) if `actionlint` provided `ExecInvalid` kind for steps that are known to be incorrect
https://github.com/nektos/act/blob/b910a42edfab7a02b08a52ecef203fd419725642/pkg/model/workflow.go#L378-L411

**Comment by rhysd** [comment]
After checking implementation, it seems that adding this is not necessary. When an invalid value is set as a step object, `step.Exec` is not set. So you can check the step is invalid by checking `nil` like `step.Exec == nil`.
